[phases.setup]
nixPkgs = ['nodejs_23', 'pnpm']

[phases.install]
cmds = ['rm -rf node_modules && pnpm install --frozen-lockfile']

[phases.build]
cmds = [
    'rm -rf dist && pnpm build',
    'mkdir -p client/src/config',
    'chmod 777 client/src/config',  # Full access for all users
    'touch client/src/config/grove-uris.json',
    'chmod 666 client/src/config/grove-uris.json'
]
cacheDirectories = ['node_modules/.cache']

[start]
cmd = 'pnpm start'

[variables]
NODE_ENV = 'production'